Migrate to Micronaut 4.0.0 and build plugins to 6.2.0
micronaut-projects/micronaut-chatbots pull request #45
Opened 2023-01-17 19:11 UTC by wetted

2023-01-18 13:30 UTC, timyates requested changes

2023-01-18 13:30 UTC, timyates commented on buildSrc/src/main/groovy/io.micronaut.build.internal.chatbots-api.gradle
> +    api(mn.jackson.annotations)
```suggestion
    api(mnSerde.micronaut.serde.jackson)
```

2023-01-18 13:30 UTC, timyates commented on buildSrc/src/main/groovy/io.micronaut.build.internal.chatbots-api.gradle
> +    testImplementation(mnSerde.micronaut.serde.api)
We shouldn't need this as it's an `api` dependency already

2023-01-18 13:30 UTC, timyates commented on buildSrc/src/main/groovy/io.micronaut.build.internal.chatbots-base.gradle
> +}
Do we need this?

2023-01-18 13:30 UTC, timyates commented on buildSrc/src/main/groovy/io.micronaut.build.internal.chatbots-module.gradle
> +    testImplementation(mn.micronaut.jackson.databind)
```suggestion
    testImplementation(mnSerde.micronaut.serde.jackson)
```

2023-01-18 16:19 UTC, timyates approved these changes

2023-01-19 10:46 UTC, sdelamo approved these changes

2023-01-19 10:46 UTC, merged